# Generated by Django 4.1.3 on 2022-12-15 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2, 'Занадто мале значеня'), django.core.validators.MaxLengthValidator(40, 'Занадто велике значеня')])),
                ('about_item', models.TextField(blank=True, max_length=600)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
