apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - image: bra1let/djangodevops:0.2
          name: django
          command: [ "/bin/sh","-c" ]
          args:
            - python manage.py makemigrations; 
              python manage.py makemigrations appsch;
              python manage.py migrate; 
              python manage.py migrate appsch;
              gunicorn --bind :8000 --workers 3 Servicedjango.wsgi;
          ports:
            - containerPort: 8000
              name: gunicorn
          livenessProbe:
             httpGet:
               path: /
               port: 8000
             initialDelaySeconds: 2
             periodSeconds: 3