apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - image: bra1let/djangopp:v1.4
          name: django
          command: ["gunicorn", "--bind", ":8000", "--workers", "3", "Schedule.wsgi"]
          ports:
            - containerPort: 8000
              name: gunicorn