apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
        - name: django
          image: bra1let/django-applab2:v1.0
          command: ['python', 'manage.py', 'migrate']
      restartPolicy: Never
  backoffLimit: 5
