name: Lint and Push to DockerHub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
 
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tonybajan/flake8-check-action@v1.3.0
      with:
        select: E3,E4,E5,E7,W6,F,B,G0
        maxlinelength: 100
        repotoken: ${{ secrets.TOKEN_GITHUB }}


  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          cd services/svc
          docker build -t ${{secrets.DOCKERHUB_USER}}/djangodevops:latest .

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{secrets.DOCKERHUB_USER}}/djangodevops:latest
          push: true
  ping:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull ${{secrets.DOCKERHUB_USER}}/djangodevops:latest
      - name: Run image
        run: docker run -p 8000:80 -d ${{secrets.DOCKERHUB_USER}}/djangodevops
      - name: Wait for build
        run: sleep 5
      - name: Ping
        run: curl localhost
